const movies = [
  {
    image: "https://placehold.co/600x400",
    title: "The Lord of the Rings: The Fellowship of the Ring",
    release_year: 2001,
    rating: 4.4,
    genre_id: 3,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    image: "https://placehold.co/600x400",
    title: "The Godfather",
    release_year: 1972,
    rating: 4.7,
    genre_id: 5,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    image: "https://placehold.co/600x400",
    title: "The Dark Knight",
    release_year: 2008,
    rating: 4.6,
    genre_id: 2,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    image: "https://placehold.co/600x400",
    title: "Pulp Fiction",
    release_year: 1994,
    rating: 4.5,
    genre_id: 10,
    created_at: new Date(),
    updated_at: new Date(),
  },
    {
    image: "https://placehold.co/600x400",
    title: "The Good, the Bad and the Ugly",
    release_year: 1966,
    rating: 4.4,
    genre_id: 11,
    created_at: new Date(),
    updated_at: new Date(),
  }, 
  {
    image: "https://placehold.co/600x400",
    title: "Forrest Gump",
    release_year: 1994,
    rating: 4.4,
    genre_id: 5,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    image: "https://placehold.co/600x400",
    title: "Inception",
    release_year: 2010,
    rating: 4.4,
    genre_id: 9,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    image: "https://placehold.co/600x400",
    title: "Ricky and Morty",
    release_year: 2013,
    rating: 4.5,
    genre_id: 8,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    image: "https://placehold.co/600x400",
    title: "Star Wars: Episode IV - A New Hope",
    release_year: 1977,
    rating: 4.4,
    genre_id: 7,
    created_at: new Date(),
    updated_at: new Date(),
  }
];

module.exports = movies;
